download_folder: /opt
postgres_repo_rpm_name: pgdg-redhat-repo-latest.noarch.rpm
postgres_repo_download_url: http://yum.postgresql.org/9.6/redhat/rhel-6-x86_64/{{postgres_repo_rpm_name}}
postgres_repo_rpm_location: "{{download_folder}}/{{ postgres_repo_rpm_name}}"
postgres_version: 9.6
postgresql_data_dir: /var/lib/pgsql
postgresql_packages:
  - python-psycopg2
  - postgresql96-contrib
  - postgresql96-server
  - postgresql10-libs

# ------------------------------------------------
# PostgreSQL configuration file - postgresql.conf
# ------------------------------------------------

# - Connection Settings -
postgres_conf_max_connections: 100

# - Memory -
postgres_conf_shared_buffers: 512MB
postgres_conf_work_mem: 32MB


# ------------------------------------------------
# PostgreSQL configuration file - pg_hba.conf
# ------------------------------------------------

postgres_hba_configurations:
# TYPE  DATABASE        USER            ADDRESS                 METHOD
- 'local   all             all                                 md5'
- 'host    all             all             0.0.0.0/0               md5'
- 'host    all             all             ::0/0                   md5'
